### ISSUE TITLE
Repositories typing contradiction

### ISSUE THREAD

**Issue by zerkms** [thephpleague/oauth2-server#1018] opened 2019-06-10 05:13 UTC
The `ClientRepositoryInterface` is currently implemented as https://github.com/thephpleague/oauth2-server/blob/master/src/Repositories/ClientRepositoryInterface.php

```php
interface ClientRepositoryInterface extends RepositoryInterface
{
    /**
     * Get a client.
     *
     * @param string      $clientIdentifier   The client's identifier
     * @param null|string $grantType          The grant type used (if sent)
     * @param null|string $clientSecret       The client's secret (if sent)
     * @param bool        $mustValidateSecret If true the client must attempt to validate the secret if the client
     *                                        is confidential
     *
     * @return ClientEntityInterface
     */
    public function getClientEntity($clientIdentifier, $grantType = null, $clientSecret = null, $mustValidateSecret = true);
}
```
As you can see it declares the return type as `ClientEntityInterface`.

Now in a few places where it's used (eg https://github.com/thephpleague/oauth2-server/blob/master/src/Grant/AbstractGrant.php#L197) it usually is invoked as

```php
        $client = $this->clientRepository->getClientEntity(
            $clientId,
            $this->getIdentifier(),
            $clientSecret,
            true
        );
        if ($client instanceof ClientEntityInterface === false) {
            $this->getEmitter()->emit(new RequestEvent(RequestEvent::CLIENT_AUTHENTICATION_FAILED, $request));
            throw OAuthServerException::invalidClient();
        }
```
And that's where typing becomes contradictory: phpdoc claims that `ClientEntityInterface` is returned, but the runtime does not agree and checks it additionally.

When one provides `ClientRepositoryInterface` and uses static check tools (phpstan or psalm) the former cannot understand under what circumstances the returned value is not `ClientEntityInterface` and report assertions in unit tests as redundant.

Hence a suggestion: how about making return a union of `ClientEntityInterface | null`?

**Comment by Sephster** [comment] 2019-06-18 16:19
Hi @zerkms - thanks for raising this. It is a duplicate of #799 so I will close this issue for now in favour of tracking it there. Cheers.

**Closed by Sephster** 2019-06-18 16:19 UTC
