### ISSUE TITLE
Probable BC break between 4.1.3 and 4.1.6

### ISSUE THREAD

**Issue by rmasclef** [thephpleague/oauth2-server#914] opened 2018-06-18 14:47 UTC
Hello :)

We just updated some old php 5.4 (#shame) app deps and we encountered an error upgrading v4.1.3 to v4.1.6 ^^

Here is some log that might help:

`request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Compile Error: Can't use method return value in write context" at [...]/vendor/league/oauth2-server/src/ResourceServer.php line 141 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: Can't use method return value in write context at [..]/vendor/league/oauth2-server/src/ResourceServer.php:141)"} []`

Downgrading from v4.1.6 to v4.1.3 "fixes" the problem for now.

FYI: this error seams to appear only on php5.4 (it works great on php5.5 and 5.6).

I'd be curious to know what the problem is here :+1: 

Thanks for your help !

**Comment by Sephster** [comment] 2018-06-22 12:35
It looks like the issue is here:

https://github.com/thephpleague/oauth2-server/blob/3bec591393b1cc6a3fc02c94d18262e4ffad2e4f/src/ResourceServer.php#L141

Prior to PHP 5.5, you could only put variables inside the `empty()` function so the function call is causing the error. I will raise a fix for this as version 4 of the package should support PHP 5.4.

I would strongly encourage you to upgrade to a later version of the package though. Thanks for raising this.

**Comment by Sephster** [comment] 2018-06-23 16:48
@rmasclef I believe the issue is resolved now. I've release version 4.1.7 of the package with the bug fix. Please let me know how you get on. Thanks for reporting this.

**Closed by Sephster** 2018-06-23 16:48 UTC

**Comment by rmasclef** [comment] 2018-06-24 21:16
@sephter thanks a lot for your reactivity! i'll check by the end the week :)

**Comment by Sephster** [comment] 2018-06-25 07:29
Excellent. Please do let me know how you get on. Thanks

On 24 June 2018 22:16:53 BST, Romain Masclef <notifications@github.com> wrote:
>@sephter thanks a lot for your reactivity! i'll check by the end the
>week :)
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/thephpleague/oauth2-server/issues/914#issuecomment-399788289

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Sephster** [comment] 2018-06-30 10:29
@rmasclef did the fix work as expected?

**Comment by rmasclef** [comment] 2018-07-11 07:06
@Sephster sorry for the huge delay, I just upgraded the app deps and the problem seems to be fixed :+1:

**Comment by Sephster** [comment] 2018-07-11 16:00
Awesome. Glad it worked. Thanks for the update @rmasclef
