### ISSUE TITLE
Access Token Scope not meeting oAuth 2 specification requirements?

### ISSUE THREAD

**Issue by cvigorsICBF** [thephpleague/oauth2-server#1260] opened 2022-01-12 12:45 UTC
Hi, 
In the [client credentials docs](https://oauth2.thephpleague.com/authorization-server/client-credentials-grant/) it has the scope included in the request, but only the token_type, expires_in and access_token is included in the response. The scope is not included in the response.

What happens if a client requests a scope that they are not allowed access too?

According to the [oauth2 specification ](https://datatracker.ietf.org/doc/html/rfc6749#section-3.3),  it states that:
 "If the issued access token scope is different from the one requested by the client, the authorization server MUST include the "scope" response parameter to inform the client of the actual scope granted."

For example

A client has been granted access to scope “scope1”, but requests “scope1 scope2”

`{
    "grant_type": "client_credentials",
    "client_id" : "test",
    "client_secret" : "test_secret",
    "scope" : "scope1 scope2"
}`
The server responds with the expected fields:
`{
    "token_type": "Bearer",
    "expires_in": 86400,
    "access_token": "eyJ0eXAiOiJ........"
}`

There is nothing in the response to indicate to the client what scopes the access_token can be used for.
 
Should the response actually be: 
`{
    "token_type": "Bearer",
    "expires_in": 86400,
    "access_token": "eyJ0eXAiOiJ........",
    "scope": "scope1"
}`

**Comment by Sephster** [comment] 2022-01-24 23:26
Thanks for reporting. This does appear to not conform to the specs. Will flag this as a bug. Thanks for reporting

**Comment by Sephster** [comment] 2022-01-24 23:48
Realised this is a duplicate of #793 so closing in favour of that. Thank you for reporting though @cvigorsICBF

**Closed by Sephster** 2022-01-24 23:48 UTC
Labels: Spec Compliance
